// Code generated by protoc-gen-go.
// source: inner.proto
// DO NOT EDIT!

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	inner.proto

It has these top-level messages:
	HeartbeatReq
	HeartbeatAck
	ErrorAck
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 心跳请求0
type HeartbeatReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatReq) Reset()                    { *m = HeartbeatReq{} }
func (m *HeartbeatReq) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatReq) ProtoMessage()               {}
func (*HeartbeatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 心跳回复1
type HeartbeatAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatAck) Reset()                    { *m = HeartbeatAck{} }
func (m *HeartbeatAck) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatAck) ProtoMessage()               {}
func (*HeartbeatAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 通用的错误回复2
type ErrorAck struct {
	Errid            *int32  `protobuf:"varint,1,req,name=errid" json:"errid,omitempty"`
	Errstr           *string `protobuf:"bytes,2,req,name=errstr" json:"errstr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrorAck) Reset()                    { *m = ErrorAck{} }
func (m *ErrorAck) String() string            { return proto.CompactTextString(m) }
func (*ErrorAck) ProtoMessage()               {}
func (*ErrorAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ErrorAck) GetErrid() int32 {
	if m != nil && m.Errid != nil {
		return *m.Errid
	}
	return 0
}

func (m *ErrorAck) GetErrstr() string {
	if m != nil && m.Errstr != nil {
		return *m.Errstr
	}
	return ""
}

func init() {
	proto.RegisterType((*HeartbeatReq)(nil), "services.heartbeat_req")
	proto.RegisterType((*HeartbeatAck)(nil), "services.heartbeat_ack")
	proto.RegisterType((*ErrorAck)(nil), "services.error_ack")
}

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcc, 0xcb, 0x4b,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0x2d, 0x56, 0xe2, 0xe7, 0xe2, 0xcd, 0x48, 0x4d, 0x2c, 0x2a, 0x49, 0x4a, 0x4d, 0x2c, 0x89, 0x2f,
	0x4a, 0x2d, 0x44, 0x15, 0x48, 0x4c, 0xce, 0x56, 0xb2, 0xe4, 0xe2, 0x4c, 0x2d, 0x2a, 0xca, 0x2f,
	0x02, 0x71, 0x84, 0x44, 0xb8, 0x58, 0x81, 0x9c, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x26, 0x0d, 0xd6,
	0x20, 0x08, 0x47, 0x48, 0x8c, 0x8b, 0x0d, 0xc8, 0x28, 0x2e, 0x29, 0x92, 0x60, 0x02, 0x0a, 0x73,
	0x06, 0x41, 0x79, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xd5, 0x5e, 0x22, 0x74, 0x00, 0x00,
	0x00,
}
